{"name": "test_create_double_user_return_status_code_403", "status": "passed", "description": "Проверка невозможности создании пользователя, когда он уже зарегистрирован.Получаем ошибку 403", "steps": [{"name": "Создание нового пользователя в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'anike_45@example.com', 'password': 'l2wPtEvt@_', 'name': 'Эраст Алексеевич Игнатьев'}"}], "start": 1719740938140, "stop": 1719740938764}], "start": 1719740938140, "stop": 1719740938764, "uuid": "a357d66f-efcb-4d58-9bd8-175a00713c58", "historyId": "121f443b42b2d6885bb4e284f49440b5", "testCaseId": "121f443b42b2d6885bb4e284f49440b5", "fullName": "tests.test_create_user.TestCreateUser#test_create_double_user_return_status_code_403", "labels": [{"name": "story", "value": "Ручка /api/auth/register"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "11256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}